version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  django32:
  
    build: ./django32
    volumes:
      - ./shared:/app
    depends_on:
      - redis

  django40:
    build: ./django40
    volumes:
      - ./shared:/app
    depends_on:
      - redis
